version: '3.5'

networks:
  basic:
    name: net_basic

services:
  ca.kz:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kz
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank1.kz-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bank1.kz/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.kz
    networks:
      - basic

  orderer.kz:
    container_name: orderer.kz
    image: hyperledger/fabric-orderer:1.4.7
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/kz/orderers/orderer.kz/:/etc/hyperledger/msp/orderer
        - ./orderer.kz:/var/hyperledger/production/orderer
    networks:
      - basic

  peer.bank1.kz:
    container_name: peer.bank1.kz
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer.bank1.kz
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Bank1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer.bank1.kz:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_basic
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bank1.kz/peers/peer0.bank1.kz/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/bank1.kz/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./peer.bank1.kz:/var/hyperledger/production/orderer
    depends_on:
      - orderer.kz
  #    - couchdb
    networks:
      - basic

  peer.bank2.kz:
    container_name: peer.bank2.kz
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer.bank2.kz
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Bank2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer.bank2.kz:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_basic
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bank2.kz/peers/peer0.bank2.kz/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/bank2.kz/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./peer.bank2.kz:/var/hyperledger/production/orderer
    depends_on:
      - orderer.kz
 #     - couchdb
    networks:
      - basic

  peer.bank3.kz:
    container_name: peer.bank3.kz
    image: hyperledger/fabric-peer:1.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer.bank3.kz
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Bank3MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer.bank3.kz:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_basic
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 6051:7051
      - 6053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bank3.kz/peers/peer0.bank3.kz/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/bank3.kz/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./peer.bank3.kz:/var/hyperledger/production/orderer
    depends_on:
      - orderer.kz
#      - couchdb
    networks:
      - basic

  # couchdb:
  #   container_name: couchdb
  #   image: hyperledger/fabric-couchdb
  #   environment:
  #     - COUCHDB_USER=
  #     - COUCHDB_PASSWORD=
  #   ports:
  #     - 5984:5984
  #   networks:
  #     - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.7
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer.bank1.kz:7051
      - CORE_PEER_LOCALMSPID=Bank1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bank1.kz/users/Admin@bank1.kz/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../vat-chaincode/:/opt/gopath/src/github.com/chaincode/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/configtx/
    networks:
        - basic
